[workspace]
authors = ["alejandrodomin <a283le.programmer@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "immich-cli"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=25.6.0.dev2025080505,<26"

[activation.env]
MOJO_ENABLE_STACK_TRACE_ON_ERROR="true"
